mod JumpAerial;
mod Float;
mod Fly;
pub mod GlideStart;
pub mod Glide;
pub mod GlideAttack;
pub mod GlideEnd;
pub mod GlideLanding;
mod Sub_Glide_Checks;
mod Catch;
mod Guard;
mod Guard_On;
mod Guard_Damage;
mod Dash;
mod AttackDash;
mod Edge_Cancel;
mod SpecialHi;
mod EscapeAir;
mod Rebirth;
//mod Dead;
//mod Damage;

pub fn install() {
    JumpAerial::install();
    Float::install();
    Fly::install();
    GlideStart::install();
    Glide::install();
    GlideAttack::install();
    GlideEnd::install();
    GlideLanding::install();
    Sub_Glide_Checks::install();
    Catch::install();
    Guard::install();
    Guard_On::install();
    Guard_Damage::install();
    Dash::install();
    AttackDash::install();
    Edge_Cancel::install();
    SpecialHi::install();
    EscapeAir::install();
    Rebirth::install();
    //Dead::install();
    //Damage::install();
}