pub mod BuildImports {
    pub use {
        std::mem,
        smashline::*,    
        smashline::{Agent, Main, Pre, Init, Exec, End, Exit, ExecStop, original_status},   
        smash_script::{*, macros::*},
        interpolation::lerp,
        smash::app::{*, 
            lua_bind::{*, 
                KineticEnergy, 
                KineticEnergyNormal,
                FighterCutInManager,
                FighterManager,
                BattleObjectWorld,
                BattleObjectManager,
                AttackData,
                StageManager,
                BossManager,
                Item,
                ItemManager,
                ItemParamAccessor,
                LinkEventMask,
                LinkEventThrow,
                LinkEventStarShot,
                LinkEventCaptureFishingrodDamage,
                FighterKineticEnergyMotion,
                FighterKineticEnergyGravity,
                FighterRyuLinkEventFinalMoveTarget,
                FighterSpiritsSupportSkill,
                FighterInklingLinkEventPaint,
                GimmickEventSpring,
                GimmickEventTornadoMoveInfo,
                GimmickEventBarrel,
                GimmickEventDrumRelease,
                GimmickEventLadder
            },
            Fighter, 
            sv_information    
        },
        smash::phx::{Hash40, Vector2f, Vector3f, Vector4f},
        smash::hash40,
        smash::lib::{
            L2CAgent,
            L2CValue,
            lua_const::*,
            L2CValueType::*, 
            L2CValueType, 
            L2CTable, 
            L2CTable_meta, 
            L2CInnerFunctionBase, 
            L2CValueInner
        },
        smash::lib::lua_const::EffectScreenLayer::{GROUND, CHAR},
        smash::lua2cpp::{*, L2CAgentBase, L2CFighterCommon, L2CFighterBase},
        singletons::*,
        smash::app::sv_animcmd::{
            frame, 
            wait, 
            execute,
            get_value_float, 
            get_value_int,  
            wait_loop, 
            stop, 
            wait_loop_sync_mot, 
            frame_clear,
            FT_START_CUTIN_arg1,
            SET_SPEED,
            CHECK_FINISH_CAMERA_IF_NOT_HP_MODE,
            SET_AIR,
        },
        crate::globals::*,
        crate::common::{*,
            consts::*,
            function::{*, KineticUtility},
            frame::frame_common,
            FIGHTER_BOOL_1,
            FIGHTER_BOOL_2,
            FIGHTER_BOOL_3,
            get_player_number,
        },
        crate::utils::{*, FIGHTER_CUTIN_MANAGER, get_entry_id},
        crate::helper::{
            ADD_SPEED_NO_LIMIT,
            FT_CATCH_STOP,
            FT_REMOVE_FINAL_AURA,
            LAST_EFFECT_SET_WORK_INT,
            EFFECT_OFF_HANDLE,
            FT_IS_SAME_FIGHTER_CATEGORY,
            EFFECT_FOLLOW_FLIP_arg13,
            EFFECT_BRANCH_SITUATION,
            EFFECT_GLOBAL,
            DOWN_EFFECT,
            FT_ATTACK_ABS_CAMERA_QUAKE,
            IS_EXIST_ARTICLE,
            CLR_SPEED,
            REG_LANDING_SE,
            SET_RATE_ARTICLE,
            EFFECT_FOLLOW_RND,
            REQ_MOTION_CAMERA,
            CHECK_VALID_START_CAMERA,
            SET_TAKEOUT_SE_STATUS,
            EFFECT_FOLLOW_COLOR
        },
        skyline::{c_str, from_c_str, nn::ro::LookupSymbol},
        skyline::nro::{self, NroInfo},
        std::f32::consts::PI,
        smash2,
        smash2::app::BattleObjectModuleAccessor,
        skyline::hooks::InlineCtx,
    };
}