use crate::imports::BuildImports::*;

//COMMON
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ASDI_START: i32 = 495;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_AUTO_COUNTER: i32 = 496;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_B_CHECK: i32 = 497; //Tracks if a fighter used a certain special move in the air
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_ADD: i32 = 498;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED: i32 = 499;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED_PREVENT: i32 = 500;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DID_MAX_JUMP_COUNT: i32 = 501;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FIGHTER_SPECIAL_STATE: i32 = 502;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FULL_SMASH_ATTACK: i32 = 503;
pub const FIGHTER_INSTANCE_WORK_ID_INT_GOT_HIT: i32 = 504; //Tracks if a player got hit during One-Hit mode
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HITFLOW: i32 = 505;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_IS_WAVEDASH: i32 = 506;
pub const FIGHTER_INSTANCE_WORK_ID_INT_MASHING: i32 = 507;
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRIED: i32 = 508;
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRY_TIMER: i32 = 509;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_READY_GO: i32 = 510; //Returns false for exactly one frame after is_ready_go becomes true, used to initiate certain events exactly once at the start of a match
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_BREAK_TIMER: i32 = 511;
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_EFFECT_TIMER: i32 = 512;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SHIELD_SPECIAL: i32 = 513;
pub const FIGHTER_INSTANCE_WORK_ID_INT_SPECIAL_ZOOM_GFX: i32 = 514;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_USED_FS: i32 = 515; //Flags when you just used a Final Smash in Special Smash
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_WAVEDASH_DONE: i32 = 516;
pub const FIGHTER_INSTANCE_WORK_ID_INT_CLIFF_XLU_FRAME: i32 = 517;
pub const FIGHTER_INSTANCE_WORK_ID_INT_LANDING_FRAME: i32 = 518;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_S4_IS_CHARGED: i32 = 519;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_HI4_IS_CHARGED: i32 = 520;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_LW4_IS_CHARGED: i32 = 521;
pub const FIGHTER_INSTANCE_WORK_ID_INT_EFFECT_COUNTER: i32 = 522;
pub const FIGHTER_INSTANCE_WORK_ID_INT_SOUND_COUNTER: i32 = 523;
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_EFFECT_SCALE_MUL: i32 = 524;
pub const FIGHTER_STATUS_ATTACK_WORK_FLAG_CRITICAL: i32 = 0x100000B;
pub const FIGHTER_STATUS_GLIDE_WORK_INT_PITCH_SE: i32 = 0x11000007;
pub const FIGHTER_STATUS_GLIDE_WORK_INT_STOP_SE: i32 = 0x11000008;
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_N: i32 = 0x21000023;
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_S: i32 = 0x21000024;
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_HI: i32 = 0x21000025;
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_LW: i32 = 0x21000026;

//BASYAAMO
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_N_OVERHEAT: i32 = 0x1F3;
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_HI_OVERHEAT: i32 = 0x1EE;
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_LW2: i32 = 0x1EF;
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_LW_LOOP: i32 = 0x1F0;
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_LW_LANDING: i32 = 0x1F1;
pub const FIGHTER_BASYAAMO_STATUS_KIND_SPECIAL_LW_AIR_END: i32 = 0x1F2;

//LINK
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_URBOSA_FURY: i32 = 0x200000E9;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_SPIN_ATTACK_CAN_FALL: i32 = 0x200000EA;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_PICK_ITEM: i32 = 0x200000EB;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_BOMB_FUSED: i32 = 0x200000EC;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_CAN_ASCEND: i32 = 0x200000ED;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: i32 = 0x100000C6;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_TEAM_NO: i32 = 0x100000C7;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE: i32 = 0x100000C8;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE: i32 = 0x100000C9;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE_ID: i32 = 0x100000CA;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_ASCEND_FRAME: i32 = 0x100000CB;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_JUMP_BUTTON_ON_FRAME: i32 = 0x100000CC;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_ASCEND_START_Y: i32 = 0x100000CB;
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_ASCEND_TARGET_Y: i32 = 0x100000CC;
pub const FIGHTER_LINK_STATUS_KIND_ATTACK_DASH_BOUND: i32 = 0x1E9;
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE: i32 = 0x1EA;
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_TURN: i32 = 0x1EB;
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_DROP: i32 = 0x1EC;
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_LANDING: i32 = 0x1ED;
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_START: i32 = 0x1EE;
pub const FIGHTER_LINK_STATUS_KIND_ASCEND: i32 = 0x1EF;
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_END: i32 = 0x1F0;
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_JUMP_GROUND: i32 = 0x1F1;
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_JUMP_GROUND_END: i32 = 0x1F2;
pub const FIGHTER_LINK_GENERATE_ARTICLE_CLAWSHOT: i32 = 0x9;
pub const FIGHTER_LINK_GENERATE_ARTICLE_CLAWSHOT_HAND: i32 = 0xA;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_KIND: i32 = 0x1000000E;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_FLAG: i32 = 0x1000000F;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_STATUS: i32 = 0x10000010;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: i32 = 0x10000011;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_ITEM_FUSED: i32 = 0x20000009;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_FUSE_REFLECT: i32 = 0x2000000A;
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_FUSE_DEDEDE_SWALLOW: i32 = 0x2000000B;
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_KIND: i32 = 0x1000000C;
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_STATUS: i32 = 0x1000000D;
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: i32 = 0x1000000E;
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_FLAG_ITEM_FUSED: i32 = 0x2000000E;
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_FLAG_FUSE_REFLECT: i32 = 0x2000000F;

//KIRBY
pub const FIGHTER_KIRBY_STATUS_KIND_SPECIAL_HI_H: i32 = 0x3E6;
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE: i32 = 0x1000010B;
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_TEAM_NO: i32 = 0x1000010C;

//MARIO
pub const FIGHTER_MARIO_STATUS_SPECIAL_N_FLAG_SPECIAL_N_GIANT_FIREBALL: i32 = 0x2100000E;
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_INT_SPECIAL_BUTTON_ON_FRAME: i32 = 0x100000BF;

//METAKNIGHT
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_N: i32 = 0x200000E6;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_S: i32 = 0x200000E7;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_HI: i32 = 0x200000E8;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_LW: i32 = 0x200000E9;
pub const FIGHTER_METAKNIGHT_STATUS_KIND_SPECIAL_GUARD: i32 = 0x1F0;
pub const FIGHTER_METAKNIGHT_GENERATE_ARTICLE_GALAXIA_BEAM: i32 = 0x3;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_GUARD: i32 = 0x200000E5;
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_META_POWER: i32 = 0x200000EA;  
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_STATUS_KIND_SHOOT: i32 = 0x0;
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_STATUS_KIND_END: i32 = 0x1;
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_INSTANCE_WORK_ID_FLOAT_ANGLE: i32 = 0x1;
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_INSTANCE_WORK_ID_FLOAT_ROT: i32 = 0x2;

//MURABITO
pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_ARROW_FUSE_ITEM: i32 = 0x100000D1;
pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_BOOMERANG_FUSE_ITEM: i32 = 0x100000D2;
pub const FIGHTER_MURABITO_INSTANCE_WORK_ID_INT_LINK_BOOMERANG_FUSE_ITEM_ID: i32 = 0x100000D3;
pub const FIGHTER_MURABTIO_INSTANCE_WORK_ID_INT_TEAM_NO: i32 = 0x100000D4;

//PIT
pub const FIGHTER_PIT_STATUS_KIND_SPECIAL_HI_FLY: i32 = 0x1D3;
pub const FIGHTER_PIT_STATUS_KIND_SPECIAL_HI_FLY_TURN: i32 = 0x1EF;
pub const FIGHTER_PIT_STATUS_KIND_SPECIAL_HI_FLY_END: i32 = 0x1F0;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLOAT_GRAVITY: i32 = 0x100000E;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLOAT_SPEED_X: i32 = 0x100000F;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLOAT_SPEED_Y: i32 = 0x1000010;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_TIME: i32 = 0x1000011;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_LAND_TIME: i32 = 0x1000012;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_START_SE: i32 = 0x1000013;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_START_SE_COUNTER: i32 = 0x1000014;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLAG_TURN: i32 = 0x1000014;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLAG_BURN: i32 = 0x1000015;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLOAT_TURN_DIR: i32 = 0x1000016;
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLOAT_ROT_Y: i32 = 0x1000017;

//PLIZARDON
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_HI2: i32 = 0x1DB;
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_HI2_LANDING: i32 = 0x1D3;
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_GUARD: i32 = 0x1D2;
pub const FIGHTER_PLIZARDON_STATUS_ROCKSTONE_WORK_INT_INTERVAL_FRAME_COUNT: i32 = 0x11000011;
pub const FIGHTER_PLIZARDON_STATUS_ROCKSTONE_FLAG_GENE_ROCK: i32 = 0x21000010;
pub const FIGHTER_PLIZARDON_GENERATE_ARTICLE_ROCK: i32 = 3;
pub const WEAPON_PLIZARDON_ROCK_STATUS_KIND_START: i32 = 0;
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_FLAG_BREAK: i32 = 0x2000000B;
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_SPAWN_COOLDOWN: i32 = 0x1000000A;
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_STONES_MAX: i32 = 0x10000004;
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_STONES_REMAIN: i32 = 0x10000005;
pub const FIGHTER_PLIZARDON_GENERATE_ARTICLE_ROCKSTONE: i32 = 4;
pub const WEAPON_PLIZARDON_ROCKSTONE_STATUS_KIND_START: i32 = 0x0;
pub const WEAPON_PLIZARDON_ROCKSTONE_STATUS_KIND_MOVE: i32 = 2;
pub const WEAPON_PLIZARDON_ROCKSTONE_INSTANCE_WORK_ID_FLOAT_ANGLE: i32 = 0x10000009;
pub const WEAPON_PLIZARDON_ROCKSTONE_INSTANCE_WORK_ID_FLOAT_ROT: i32 = 0x1000000B;

//PZENIGAME
pub const FIGHTER_PZENIGAME_STATUS_KIND_SPECIAL_GUARD: i32 = 0x1D3;

//PFUSHIGISOU
pub const FIGHTER_PFUSHIGISOU_STATUS_KIND_SPECIAL_GUARD: i32 = 0x1D3;
pub const FIGHTER_PFUSHIGISOU_STATUS_KIND_SPECIAL_GUARD_SHOOT: i32 = 0x1DA;
pub const FIGHTER_PFUSHIGISOU_STATUS_KIND_SPECIAL_GUARD_END: i32 = 0x1DB;
pub const FIGHTER_PFUSHIGISOU_STATUS_SPECIAL_GUARD_WORK_INT_CHARGE: i32 = 0x21000015;
pub const FIGHTER_PFUSHIGISOU_STATUS_SPECIAL_GUARD_FLAG_CHARGE: i32 = 0x21000016;

//DIDDY
pub const FIGHTER_DIDDY_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_LAUGH_TRIGGER: i32 = 0x200000E4;
pub const FIGHTER_DIDDY_INSTANCE_WORK_ID_INT_BANANA_ID: i32 = 0x200000E5;

//LUCARIO
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_ENABLE_SPECIAL_HI: i32 = 0x200000E3;
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_HI: i32 = 0x200000E4;

//LUCINA
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_LW_HIT2: i32 = 0x1EF;
pub const FIGHTER_LUCINA_STATUS_SPECIAL_LW_FLAG_ACTIVATE_SPECIAL_LW_HIT2: i32 = 0x2100001F;

//RYU
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_START: i32 = 0x202;
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_CHARGE: i32 = 0x203;
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_FIRE: i32 = 0x204;
pub const FIGHTER_RYU_STATUS_WORK_ID_KAMEHAMEHA_FLOAT_CHARGE_TIME: i32 = 0x2100001C;

//SILVER
pub const FIGHTER_SILVER_STATUS_SPECIAL_N_WORK_FLOAT_ANGLE: i32 = 0x100000C;
pub const FIGHTER_SILVER_GENERATE_ARTICLE_BOX: i32 = 0x4;
pub const WEAPON_SILVER_BOX_STATUS_KIND_BREAK: i32 = 0x1;
pub const WEAPON_SILVER_BOX_STATUS_KIND_START: i32 = 0x2;

//SIMON & RICHTER
pub const FIGHTER_SIMON_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_HI: i32 = 0x200000F7;

//TRAIL
pub const FIGHTER_TRAIL_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_S: i32 = 0x200000E6;

//WALUIGI
pub const FIGHTER_WALUIGI_GENERATE_ARTICLE_DICEBLOCK: i32 = 0x4;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_S: i32 = 0x1D3;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_S_DIVE: i32 = 0x1D2;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_S_LANDING: i32 = 0x1D1;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_LW_GUARD: i32 = 0x1D0;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_LW_ATTACK: i32 = 0x1D5;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_LW_JUMP: i32 = 0x1CF;
pub const FIGHTER_WALUIGI_STATUS_KIND_SPECIAL_LW_SPECIAL: i32 = 0x1C0;
pub const WEAPON_WALUIGI_DICEBLOCK_STATUS_KIND_BREAK: i32 = 0x1;
pub const WEAPON_WALUIGI_DICEBLOCK_STATUS_KIND_DIE: i32 = 0x2;

//WOLF
pub const FIGHTER_WOLF_STATUS_KIND_SPECIAL_S_RUSH: i32 = 0x1EA;
pub const FIGHTER_WOLF_STATUS_KIND_SPECIAL_S_END: i32 = 0x1EB;